/* GENERATED — do not hand-edit. Regenerate: uv run --python .venv python -m active_loop.site_data --lab-status */
window.AM_LAB_STATUS = {
  latest_exp: { n: 206, title: "N5 SENSE-EVOLUTION sub-arc: the ROTATING-CLASS NICHE / SYMPATRIC-DIVERGENCE BRIDGE — the LAST structurally-distinct escape (a private, time-rotating, crowding-discounted niche) FAILS too: precision stays primitive (h decays 0.10→0.027) at a SURVIVABLE population with NO collapse confound — the cleanest wall of the arc; the local selection gradient is ≤0 even with a private niche", tag: "NEGATIVE" },
  tally: { total: 206, positive: 114, negative: 59, mixed: 29, breakthroughs: 7 },
  directions: [
    { name: "active-monkey-mechanisms", state: "active", latest: "suite scaffold", next: "run suite as a numbered Loop B experiment with raw output and append-only verdict" },
    { name: "population-ecology", state: "active (sub-arc CONVERGED — awaiting human steer)", latest: "Exp 206 (NEGATIVE / NEW INSIGHT — the SIXTH wall, cleanest in the arc, blind-verified 3/3: the LAST structurally-distinct escape — a private time-ROTATING crowding-discounted NICHE, 17-agent design+audit-hardened — FAILS too; precision decays 0.10→0.027 [0/5 functional, h*=0.0, pairwise 3/8] at a SURVIVABLE pop [min 586], so the failure is PURELY the local gradient ≤0, NO collapse confound; six escapes converge — a costed sense is un-evolvable here) · SENSE-EVOLUTION (203–206), escapes EXHAUSTED", next: "" },
    { name: "red-team", state: "active", latest: "TBD-human", next: "pick 3 strongest claims (Exp 20/26/34 candidates) and run the trivial baseline each lacked (random policy, shuffled history, shuffled labels)" },
    { name: "meta-calibration-n3", state: "halted (K chapter closed, fully graded; next move awaits a word)", latest: "Exp 173", next: "on a word — synthesis fold-in then N4 / M4a-1c / nira switch / cloud merge, or a named crack" },
    { name: "n4-crack-edges", state: "halted (PAUSED on human's word after Exp 193; CONSULT in loop/IDEAS.md)", latest: "Exp 193 — position null; locality re-named stream composition; falsifier fires vacuous", next: "ON A WORD — (a) quiet-chamber stream intervention [RECOMMENDED]; (b) stream-conditioned scoring; (c) accept + rung 2; (d) redirect" },
    { name: "continuous-creature", state: "flagship-candidate", latest: "Exp 154", next: "full-scale worldview bench under predeclared bars.json (experiments/bench_worldview/), and the standing consult on applying the normalized-predictive switch to nira" },
    { name: "functional-emergence", state: "exploratory", latest: "TBD-human", next: "build and validate surprise-ledger instrument on baseline epoch and planted-anomaly control" },
    { name: "graded-uncertainty", state: "exploratory", latest: "TBD-human", next: "Rung 1 no-harm test: λ-creature vs non-decay twin on static world with predeclared effect-size bands" },
    { name: "persistent-creature", state: "exploratory", latest: "TBD-human", next: "Exp 41 BIRTH: map accuracy >= 8/9 cells correctly represented in committed belief" },
    { name: "relational-thoughts", state: "exploratory", latest: "TBD-human", next: "Rung 1 two-hop spatial: creature learns \"object at place P\" and \"P is in room R\"; query \"which room is the object in?\" without co-observing object+room; FAIL = answer at chance" },
    { name: "sequence-substrate", state: "exploratory", latest: "TBD-human", next: "Rung 1 AIF pair-state (trigram) model: reproduce taught Q→A inside active inference proper; FAIL = pair-state model can't reproduce what template already does" },
    { name: "social-emergence", state: "exploratory", latest: "TBD-human", next: "Rung 1 clade infrastructure: fork mirro into second committed line, verify lineage records shared-ancestor hash, both independently resumable, trunk byte-identical" },
    { name: "transfer", state: "exploratory", latest: "TBD-human", next: "Rung 1 same world, new geometry: creature with learned 4x4 map dropped into different 4x4 layout; FAIL = no difference vs fresh creature" },
    { name: "continuous-substrate", state: "closed-positive", latest: "Exp 138–140", next: "TBD-human" },
    { name: "identity-n4-crack", state: "closed-positive (CLOSED 2026-06-12)", latest: "Exp 188–190 — crack REAL → closed on continuity clock → regulation ties at fixed-L → defends uniquely at variable-L but cannot revise → rung-6 NEGATIVE; synthesis docs/research/n4-crack-chapter.md §8", next: "ON A WORD — variable-L geometry, tight-tolerance core, or post-release retention (§6 edges 2–3)" },
    { name: "identity-n4", state: "closed-negative", latest: "Exp 183 — regulated commitment vs any constant FAILED kill test; defense-as-config documented; chapter graded on human's word", next: "TBD-human (seed-229/variable-length crack deferred, or untried anchor form)" },
  ],
  flagship: { title: "Agents That Know When Their Worldview Is Too Small", page: "docs/flagship/worldview-too-small.md" }
};
