/* GENERATED — do not hand-edit. Regenerate: uv run --python .venv python -m active_loop.site_data --lab-status */
window.AM_LAB_STATUS = {
  latest_exp: { n: 192, title: "n4-crack-edges rung 1 completion attempt (pre-registered a2e1e1b): NEGATIVE (the stricter of two readings, blind-verified) — the PRIMARY question is INSTRUMENT-BOUNDED A SECOND TIME: even at 12,000-step tails the re-freeze cycle does not settle (36/82 defended controller seats still unmeasurable; tail freezes run 2,600 -> 9,300+ steps; 3 sessions/arm effectively unreleased at session end), so all 6 controller pairs fail the predeclared M>=10 gate and no retention rate is licensed; H-mech REFUTED in Part C (the surrendering seed carries the LARGER at-release margin, 92.4 vs 87.6 — the divergence tracks post-release observation composition, 48% vs 33% attack-color: THE LOCALITY MECHANISM); P2/P3 emphatically clean (baseline displacement total, w1=1.0 in 48/48 sessions; oracle retains 14/15 and 14/14); the rung-1 question needs REFRAMING, not a third tail extension — consult posted, loop PAUSED on the human's word", tag: "NEGATIVE" },
  tally: { total: 192, positive: 109, negative: 52, mixed: 27, breakthroughs: 5 },
  directions: [
    { name: "n4-crack-edges", state: "active (RESUMED on the human's word \"b\" — Exp 193, the return-home causal test)", latest: "Exp 192 (rung-1 instrument-bounded twice; H-mech refuted; the locality mechanism + non-settling tail named)", next: "Exp 192 — rung 1 completed with tails >= 12,000, unmeasured seats excluded from numerator AND denominator behind a >= 6-measurable validity gate, plus the s301-vs-s297 mechanism diagnostic; then rung 2 (the tight core) on its own pre-registration" },
    { name: "red-team", state: "active", latest: "TBD-human", next: "pick 3 strongest claims (Exp 20/26/34 candidates) and run the trivial baseline each lacked (random policy, shuffled history, shuffled labels)" },
    { name: "meta-calibration-n3", state: "halted (K chapter closed, fully graded; next move awaits a word)", latest: "Exp 173", next: "on a word — synthesis fold-in then N4 / M4a-1c / nira switch / cloud merge, or a named crack" },
    { name: "continuous-creature", state: "flagship-candidate", latest: "Exp 154", next: "full-scale worldview bench under predeclared bars.json (experiments/bench_worldview/), and the standing consult on applying the normalized-predictive switch to nira" },
    { name: "functional-emergence", state: "exploratory", latest: "TBD-human", next: "build and validate surprise-ledger instrument on baseline epoch and planted-anomaly control" },
    { name: "graded-uncertainty", state: "exploratory", latest: "TBD-human", next: "Rung 1 no-harm test: λ-creature vs non-decay twin on static world with predeclared effect-size bands" },
    { name: "persistent-creature", state: "exploratory", latest: "TBD-human", next: "Exp 41 BIRTH: map accuracy >= 8/9 cells correctly represented in committed belief" },
    { name: "relational-thoughts", state: "exploratory", latest: "TBD-human", next: "Rung 1 two-hop spatial: creature learns \"object at place P\" and \"P is in room R\"; query \"which room is the object in?\" without co-observing object+room; FAIL = answer at chance" },
    { name: "sequence-substrate", state: "exploratory", latest: "TBD-human", next: "Rung 1 AIF pair-state (trigram) model: reproduce taught Q→A inside active inference proper; FAIL = pair-state model can't reproduce what template already does" },
    { name: "social-emergence", state: "exploratory", latest: "TBD-human", next: "Rung 1 clade infrastructure: fork mirro into second committed line, verify lineage records shared-ancestor hash, both independently resumable, trunk byte-identical" },
    { name: "transfer", state: "exploratory", latest: "TBD-human", next: "Rung 1 same world, new geometry: creature with learned 4x4 map dropped into different 4x4 layout; FAIL = no difference vs fresh creature" },
    { name: "continuous-substrate", state: "closed-positive", latest: "Exp 138–140", next: "TBD-human" },
    { name: "identity-n4-crack", state: "closed-positive (CLOSED 2026-06-12 — the chapter's constructive closure stands and the rung-6 coda is graded NEGATIVE within it; the recommended option of the Exp 190 consult executed under the ratified resumption pattern: the rung-6 postscript — Exp 189 + Exp 190 + the three laws (kappa-reach / flicker tax / timescale overlap) — is folded into docs/research/n4-crack-chapter.md §8, blinded-fact-checked with 1 correction folded (pre-stretch count 1–4 not 1–5, the Exp 145 precedent); the crack chapter is fully graded: crack REAL → closed constructively on the continuity clock → regulation ties at fixed-L → defends uniquely at variable-L but cannot revise → unrepairable on the named channels; re-opens only on an explicit human word — the remaining open edges are the tight-tolerance core and post-release retention (chapter §6 edges 2–3)) · previously closed-positive — 9 confirmed cells; closed constructively on the continuity clock; the regulated-controller question answered at exact parity; chapter synthesis committed)", latest: "Exp 184 (exploratory squeeze map) + Exp 183 addendum (seed-229 autopsy)", next: "ON RESUMPTION — Part-3 classification of the candidate sets (is any candidate a REAL crack after the class-D dissolution check?), then rung-4 fresh-seed confirmation" },
    { name: "identity-n4", state: "closed-negative", latest: "Exp 183", next: "TBD-human (re-opens only on a word: the seed-229/variable-length crack — deferred, or the untried anchor form)" },
  ],
  flagship: { title: "Agents That Know When Their Worldview Is Too Small", page: "docs/flagship/worldview-too-small.md" }
};
