/* GENERATED — do not hand-edit. Regenerate: uv run --python .venv python -m active_loop.site_data --lab-status */
window.AM_LAB_STATUS = {
  latest_exp: { n: 191, title: "n4-crack-edges rung 1, post-release retention (pre-registered 55e7705; the human's word \"Chapter's remaining edges\"): NEGATIVE — F1 fired as predeclared, DECOMPOSED by the instrument check: the C-B fires are wholly tail-truncation (every measured seed retained, 3/3) but C-C fails even measured-only (3/4 < 5/6) on ONE genuine deferral — seed 301, both controllers identically: a settle-phase spanning freeze defends the whole train, releases at bend+2,725, and the displacement expresses FULLY post-release (w1=w2=1.0); P2/P3 clean (baseline displaced 8/8 in every cell; oracle retains 7/8 and 7/7); two NEW dynamics found: the post-release RE-FREEZE CYCLE (defended seeds re-trigger 325-600 steps after release; final release up to bend+6,550 — my 6,600 tail was undersized, 9/20 controller defense-seats unmeasured) and settle-phase false-alarm freezes (which mechanically explain CALM-H6000's precondition swing); blind-verified", tag: "NEGATIVE" },
  tally: { total: 191, positive: 109, negative: 51, mixed: 27, breakthroughs: 5 },
  directions: [
    { name: "n4-crack-edges", state: "active", latest: "Exp 191 (rung-1 NEGATIVE — deferral exists; instrument undersized for the discovered release cycle)", next: "Exp 192 — rung 1 completed with tails >= 12,000, unmeasured seats excluded from numerator AND denominator behind a >= 6-measurable validity gate, plus the s301-vs-s297 mechanism diagnostic; then rung 2 (the tight core) on its own pre-registration" },
    { name: "red-team", state: "active", latest: "TBD-human", next: "pick 3 strongest claims (Exp 20/26/34 candidates) and run the trivial baseline each lacked (random policy, shuffled history, shuffled labels)" },
    { name: "meta-calibration-n3", state: "halted (K chapter closed, fully graded; next move awaits a word)", latest: "Exp 173", next: "on a word — synthesis fold-in then N4 / M4a-1c / nira switch / cloud merge, or a named crack" },
    { name: "continuous-creature", state: "flagship-candidate", latest: "Exp 154", next: "full-scale worldview bench under predeclared bars.json (experiments/bench_worldview/), and the standing consult on applying the normalized-predictive switch to nira" },
    { name: "functional-emergence", state: "exploratory", latest: "TBD-human", next: "build and validate surprise-ledger instrument on baseline epoch and planted-anomaly control" },
    { name: "graded-uncertainty", state: "exploratory", latest: "TBD-human", next: "Rung 1 no-harm test: λ-creature vs non-decay twin on static world with predeclared effect-size bands" },
    { name: "persistent-creature", state: "exploratory", latest: "TBD-human", next: "Exp 41 BIRTH: map accuracy >= 8/9 cells correctly represented in committed belief" },
    { name: "relational-thoughts", state: "exploratory", latest: "TBD-human", next: "Rung 1 two-hop spatial: creature learns \"object at place P\" and \"P is in room R\"; query \"which room is the object in?\" without co-observing object+room; FAIL = answer at chance" },
    { name: "sequence-substrate", state: "exploratory", latest: "TBD-human", next: "Rung 1 AIF pair-state (trigram) model: reproduce taught Q→A inside active inference proper; FAIL = pair-state model can't reproduce what template already does" },
    { name: "social-emergence", state: "exploratory", latest: "TBD-human", next: "Rung 1 clade infrastructure: fork mirro into second committed line, verify lineage records shared-ancestor hash, both independently resumable, trunk byte-identical" },
    { name: "transfer", state: "exploratory", latest: "TBD-human", next: "Rung 1 same world, new geometry: creature with learned 4x4 map dropped into different 4x4 layout; FAIL = no difference vs fresh creature" },
    { name: "continuous-substrate", state: "closed-positive", latest: "Exp 138–140", next: "TBD-human" },
    { name: "identity-n4-crack", state: "closed-positive (CLOSED 2026-06-12 — the chapter's constructive closure stands and the rung-6 coda is graded NEGATIVE within it; the recommended option of the Exp 190 consult executed under the ratified resumption pattern: the rung-6 postscript — Exp 189 + Exp 190 + the three laws (kappa-reach / flicker tax / timescale overlap) — is folded into docs/research/n4-crack-chapter.md §8, blinded-fact-checked with 1 correction folded (pre-stretch count 1–4 not 1–5, the Exp 145 precedent); the crack chapter is fully graded: crack REAL → closed constructively on the continuity clock → regulation ties at fixed-L → defends uniquely at variable-L but cannot revise → unrepairable on the named channels; re-opens only on an explicit human word — the remaining open edges are the tight-tolerance core and post-release retention (chapter §6 edges 2–3)) · previously closed-positive — 9 confirmed cells; closed constructively on the continuity clock; the regulated-controller question answered at exact parity; chapter synthesis committed)", latest: "Exp 184 (exploratory squeeze map) + Exp 183 addendum (seed-229 autopsy)", next: "ON RESUMPTION — Part-3 classification of the candidate sets (is any candidate a REAL crack after the class-D dissolution check?), then rung-4 fresh-seed confirmation" },
    { name: "identity-n4", state: "closed-negative", latest: "Exp 183", next: "TBD-human (re-opens only on a word: the seed-229/variable-length crack — deferred, or the untried anchor form)" },
  ],
  flagship: { title: "Agents That Know When Their Worldview Is Too Small", page: "docs/flagship/worldview-too-small.md" }
};
